// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// AwsCredentialsRequest defines model for AwsCredentialsRequest.
type AwsCredentialsRequest struct {
	AwsSubAccountName string `json:"aws_sub_account_name"`
}

// AwsNukeAccountRequest defines model for AwsNukeAccountRequest.
type AwsNukeAccountRequest struct {
	AwsSubAccountName string `json:"aws_sub_account_name"`
}

// CaptainDomainNukeDataAndBackupsRequest defines model for CaptainDomainNukeDataAndBackupsRequest.
type CaptainDomainNukeDataAndBackupsRequest struct {
	CaptainDomain string `json:"captain_domain"`
}

// CaptainManifestsRequest defines model for CaptainManifestsRequest.
type CaptainManifestsRequest struct {
	CaptainDomain                                string `json:"captain_domain"`
	TenantDeploymentConfigurationsRepositoryName string `json:"tenant_deployment_configurations_repository_name"`
	TenantGithubOrganizationName                 string `json:"tenant_github_organization_name"`
}

// ChiselNodesDeleteRequest defines model for ChiselNodesDeleteRequest.
type ChiselNodesDeleteRequest struct {
	CaptainDomain string `json:"captain_domain"`
}

// ChiselNodesRequest defines model for ChiselNodesRequest.
type ChiselNodesRequest struct {
	CaptainDomain string `json:"captain_domain"`

	// NodeCount Number of exit nodes to create (1-6, default: 3)
	NodeCount *int `json:"node_count,omitempty"`
}

// GitHubWorkflowRunStatusRequest defines model for GitHubWorkflowRunStatusRequest.
type GitHubWorkflowRunStatusRequest struct {
	RunUrl string `json:"run_url"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// OpsgenieAlertsManifestRequest defines model for OpsgenieAlertsManifestRequest.
type OpsgenieAlertsManifestRequest struct {
	CaptainDomain  string `json:"captain_domain"`
	OpsgenieApiKey string `json:"opsgenie_api_key"`
}

// ResetGitHubOrganizationRequest defines model for ResetGitHubOrganizationRequest.
type ResetGitHubOrganizationRequest struct {
	CaptainDomain          string `json:"captain_domain"`
	CustomDomain           string `json:"custom_domain"`
	DeleteAllExistingRepos bool   `json:"delete_all_existing_repos"`
	EnableCustomDomain     bool   `json:"enable_custom_domain"`
}

// StorageBucketsRequest defines model for StorageBucketsRequest.
type StorageBucketsRequest struct {
	CaptainDomain string `json:"captain_domain"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// VersionResponse defines model for VersionResponse.
type VersionResponse struct {
	BuildTimestamp string `json:"build_timestamp"`
	CommitSha      string `json:"commit_sha"`
	GitRef         string `json:"git_ref"`
	ShortSha       string `json:"short_sha"`
	Version        string `json:"version"`
}

// CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody defines body for CreateCaptainManifestsV1CaptainManifestsPost for application/json ContentType.
type CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody = CaptainManifestsRequest

// DeleteChiselNodesV1ChiselDeleteJSONRequestBody defines body for DeleteChiselNodesV1ChiselDelete for application/json ContentType.
type DeleteChiselNodesV1ChiselDeleteJSONRequestBody = ChiselNodesDeleteRequest

// CreateChiselNodesV1ChiselPostJSONRequestBody defines body for CreateChiselNodesV1ChiselPost for application/json ContentType.
type CreateChiselNodesV1ChiselPostJSONRequestBody = ChiselNodesRequest

// GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody defines body for GetWorkflowRunStatusV1GithubWorkflowRunStatusPost for application/json ContentType.
type GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody = GitHubWorkflowRunStatusRequest

// NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody defines body for NukeAwsCaptainAccountV1NukeAwsCaptainAccountDelete for application/json ContentType.
type NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody = AwsNukeAccountRequest

// NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody defines body for NukeCaptainDomainDataV1NukeCaptainDomainDataDelete for application/json ContentType.
type NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody = CaptainDomainNukeDataAndBackupsRequest

// CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody defines body for CreateOpsgeniealertsManifestV1OpsgeniePost for application/json ContentType.
type CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody = OpsgenieAlertsManifestRequest

// ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody defines body for ResetGithubOrganizationV1ResetGithubOrganizationDelete for application/json ContentType.
type ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody = ResetGitHubOrganizationRequest

// CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody defines body for CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPost for application/json ContentType.
type CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody = AwsCredentialsRequest

// HelloV1StorageBucketsPostJSONRequestBody defines body for HelloV1StorageBucketsPost for application/json ContentType.
type HelloV1StorageBucketsPostJSONRequestBody = StorageBucketsRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateCaptainManifestsV1CaptainManifestsPostWithBody request with any body
	CreateCaptainManifestsV1CaptainManifestsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCaptainManifestsV1CaptainManifestsPost(ctx context.Context, body CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteChiselNodesV1ChiselDeleteWithBody request with any body
	DeleteChiselNodesV1ChiselDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteChiselNodesV1ChiselDelete(ctx context.Context, body DeleteChiselNodesV1ChiselDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateChiselNodesV1ChiselPostWithBody request with any body
	CreateChiselNodesV1ChiselPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateChiselNodesV1ChiselPost(ctx context.Context, body CreateChiselNodesV1ChiselPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBody request with any body
	GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GetWorkflowRunStatusV1GithubWorkflowRunStatusPost(ctx context.Context, body GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBody request with any body
	NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NukeAwsCaptainAccountV1NukeAwsCaptainAccountDelete(ctx context.Context, body NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBody request with any body
	NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	NukeCaptainDomainDataV1NukeCaptainDomainDataDelete(ctx context.Context, body NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOpsgeniealertsManifestV1OpsgeniePostWithBody request with any body
	CreateOpsgeniealertsManifestV1OpsgeniePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateOpsgeniealertsManifestV1OpsgeniePost(ctx context.Context, body CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBody request with any body
	ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ResetGithubOrganizationV1ResetGithubOrganizationDelete(ctx context.Context, body ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBody request with any body
	CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPost(ctx context.Context, body CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HelloV1StorageBucketsPostWithBody request with any body
	HelloV1StorageBucketsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HelloV1StorageBucketsPost(ctx context.Context, body HelloV1StorageBucketsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// VersionVersionGet request
	VersionVersionGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateCaptainManifestsV1CaptainManifestsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCaptainManifestsV1CaptainManifestsPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCaptainManifestsV1CaptainManifestsPost(ctx context.Context, body CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCaptainManifestsV1CaptainManifestsPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteChiselNodesV1ChiselDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteChiselNodesV1ChiselDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteChiselNodesV1ChiselDelete(ctx context.Context, body DeleteChiselNodesV1ChiselDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteChiselNodesV1ChiselDeleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateChiselNodesV1ChiselPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateChiselNodesV1ChiselPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateChiselNodesV1ChiselPost(ctx context.Context, body CreateChiselNodesV1ChiselPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateChiselNodesV1ChiselPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWorkflowRunStatusV1GithubWorkflowRunStatusPost(ctx context.Context, body GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NukeAwsCaptainAccountV1NukeAwsCaptainAccountDelete(ctx context.Context, body NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) NukeCaptainDomainDataV1NukeCaptainDomainDataDelete(ctx context.Context, body NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOpsgeniealertsManifestV1OpsgeniePostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOpsgeniealertsManifestV1OpsgeniePostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateOpsgeniealertsManifestV1OpsgeniePost(ctx context.Context, body CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOpsgeniealertsManifestV1OpsgeniePostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResetGithubOrganizationV1ResetGithubOrganizationDelete(ctx context.Context, body ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPost(ctx context.Context, body CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HelloV1StorageBucketsPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHelloV1StorageBucketsPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HelloV1StorageBucketsPost(ctx context.Context, body HelloV1StorageBucketsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHelloV1StorageBucketsPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) VersionVersionGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewVersionVersionGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateCaptainManifestsV1CaptainManifestsPostRequest calls the generic CreateCaptainManifestsV1CaptainManifestsPost builder with application/json body
func NewCreateCaptainManifestsV1CaptainManifestsPostRequest(server string, body CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCaptainManifestsV1CaptainManifestsPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCaptainManifestsV1CaptainManifestsPostRequestWithBody generates requests for CreateCaptainManifestsV1CaptainManifestsPost with any type of body
func NewCreateCaptainManifestsV1CaptainManifestsPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/captain-manifests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteChiselNodesV1ChiselDeleteRequest calls the generic DeleteChiselNodesV1ChiselDelete builder with application/json body
func NewDeleteChiselNodesV1ChiselDeleteRequest(server string, body DeleteChiselNodesV1ChiselDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteChiselNodesV1ChiselDeleteRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteChiselNodesV1ChiselDeleteRequestWithBody generates requests for DeleteChiselNodesV1ChiselDelete with any type of body
func NewDeleteChiselNodesV1ChiselDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/chisel")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateChiselNodesV1ChiselPostRequest calls the generic CreateChiselNodesV1ChiselPost builder with application/json body
func NewCreateChiselNodesV1ChiselPostRequest(server string, body CreateChiselNodesV1ChiselPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateChiselNodesV1ChiselPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateChiselNodesV1ChiselPostRequestWithBody generates requests for CreateChiselNodesV1ChiselPost with any type of body
func NewCreateChiselNodesV1ChiselPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/chisel")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequest calls the generic GetWorkflowRunStatusV1GithubWorkflowRunStatusPost builder with application/json body
func NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequest(server string, body GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequestWithBody(server, "application/json", bodyReader)
}

// NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequestWithBody generates requests for GetWorkflowRunStatusV1GithubWorkflowRunStatusPost with any type of body
func NewGetWorkflowRunStatusV1GithubWorkflowRunStatusPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/github/workflow-run-status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequest calls the generic NukeAwsCaptainAccountV1NukeAwsCaptainAccountDelete builder with application/json body
func NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequest(server string, body NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequestWithBody(server, "application/json", bodyReader)
}

// NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequestWithBody generates requests for NukeAwsCaptainAccountV1NukeAwsCaptainAccountDelete with any type of body
func NewNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/nuke-aws-captain-account")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequest calls the generic NukeCaptainDomainDataV1NukeCaptainDomainDataDelete builder with application/json body
func NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequest(server string, body NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequestWithBody(server, "application/json", bodyReader)
}

// NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequestWithBody generates requests for NukeCaptainDomainDataV1NukeCaptainDomainDataDelete with any type of body
func NewNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/nuke-captain-domain-data")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateOpsgeniealertsManifestV1OpsgeniePostRequest calls the generic CreateOpsgeniealertsManifestV1OpsgeniePost builder with application/json body
func NewCreateOpsgeniealertsManifestV1OpsgeniePostRequest(server string, body CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOpsgeniealertsManifestV1OpsgeniePostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOpsgeniealertsManifestV1OpsgeniePostRequestWithBody generates requests for CreateOpsgeniealertsManifestV1OpsgeniePost with any type of body
func NewCreateOpsgeniealertsManifestV1OpsgeniePostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/opsgenie")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequest calls the generic ResetGithubOrganizationV1ResetGithubOrganizationDelete builder with application/json body
func NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequest(server string, body ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequestWithBody(server, "application/json", bodyReader)
}

// NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequestWithBody generates requests for ResetGithubOrganizationV1ResetGithubOrganizationDelete with any type of body
func NewResetGithubOrganizationV1ResetGithubOrganizationDeleteRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/reset-github-organization")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequest calls the generic CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPost builder with application/json body
func NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequest(server string, body CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequestWithBody generates requests for CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPost with any type of body
func NewCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/setup-aws-account-credentials")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHelloV1StorageBucketsPostRequest calls the generic HelloV1StorageBucketsPost builder with application/json body
func NewHelloV1StorageBucketsPostRequest(server string, body HelloV1StorageBucketsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHelloV1StorageBucketsPostRequestWithBody(server, "application/json", bodyReader)
}

// NewHelloV1StorageBucketsPostRequestWithBody generates requests for HelloV1StorageBucketsPost with any type of body
func NewHelloV1StorageBucketsPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/storage-buckets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewVersionVersionGetRequest generates requests for VersionVersionGet
func NewVersionVersionGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateCaptainManifestsV1CaptainManifestsPostWithBodyWithResponse request with any body
	CreateCaptainManifestsV1CaptainManifestsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCaptainManifestsV1CaptainManifestsPostResponse, error)

	CreateCaptainManifestsV1CaptainManifestsPostWithResponse(ctx context.Context, body CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCaptainManifestsV1CaptainManifestsPostResponse, error)

	// DeleteChiselNodesV1ChiselDeleteWithBodyWithResponse request with any body
	DeleteChiselNodesV1ChiselDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteChiselNodesV1ChiselDeleteResponse, error)

	DeleteChiselNodesV1ChiselDeleteWithResponse(ctx context.Context, body DeleteChiselNodesV1ChiselDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteChiselNodesV1ChiselDeleteResponse, error)

	// CreateChiselNodesV1ChiselPostWithBodyWithResponse request with any body
	CreateChiselNodesV1ChiselPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateChiselNodesV1ChiselPostResponse, error)

	CreateChiselNodesV1ChiselPostWithResponse(ctx context.Context, body CreateChiselNodesV1ChiselPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateChiselNodesV1ChiselPostResponse, error)

	// GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBodyWithResponse request with any body
	GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse, error)

	GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithResponse(ctx context.Context, body GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody, reqEditors ...RequestEditorFn) (*GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse, error)

	// NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBodyWithResponse request with any body
	NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse, error)

	NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithResponse(ctx context.Context, body NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse, error)

	// NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBodyWithResponse request with any body
	NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse, error)

	NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithResponse(ctx context.Context, body NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse, error)

	// CreateOpsgeniealertsManifestV1OpsgeniePostWithBodyWithResponse request with any body
	CreateOpsgeniealertsManifestV1OpsgeniePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOpsgeniealertsManifestV1OpsgeniePostResponse, error)

	CreateOpsgeniealertsManifestV1OpsgeniePostWithResponse(ctx context.Context, body CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOpsgeniealertsManifestV1OpsgeniePostResponse, error)

	// ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBodyWithResponse request with any body
	ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse, error)

	ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithResponse(ctx context.Context, body ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse, error)

	// CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBodyWithResponse request with any body
	CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse, error)

	CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithResponse(ctx context.Context, body CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse, error)

	// HelloV1StorageBucketsPostWithBodyWithResponse request with any body
	HelloV1StorageBucketsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HelloV1StorageBucketsPostResponse, error)

	HelloV1StorageBucketsPostWithResponse(ctx context.Context, body HelloV1StorageBucketsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*HelloV1StorageBucketsPostResponse, error)

	// VersionVersionGetWithResponse request
	VersionVersionGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*VersionVersionGetResponse, error)
}

type CreateCaptainManifestsV1CaptainManifestsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateCaptainManifestsV1CaptainManifestsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCaptainManifestsV1CaptainManifestsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteChiselNodesV1ChiselDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r DeleteChiselNodesV1ChiselDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteChiselNodesV1ChiselDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateChiselNodesV1ChiselPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateChiselNodesV1ChiselPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateChiselNodesV1ChiselPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateOpsgeniealertsManifestV1OpsgeniePostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateOpsgeniealertsManifestV1OpsgeniePostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOpsgeniealertsManifestV1OpsgeniePostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HelloV1StorageBucketsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r HelloV1StorageBucketsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HelloV1StorageBucketsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type VersionVersionGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VersionResponse
}

// Status returns HTTPResponse.Status
func (r VersionVersionGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r VersionVersionGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateCaptainManifestsV1CaptainManifestsPostWithBodyWithResponse request with arbitrary body returning *CreateCaptainManifestsV1CaptainManifestsPostResponse
func (c *ClientWithResponses) CreateCaptainManifestsV1CaptainManifestsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCaptainManifestsV1CaptainManifestsPostResponse, error) {
	rsp, err := c.CreateCaptainManifestsV1CaptainManifestsPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCaptainManifestsV1CaptainManifestsPostResponse(rsp)
}

func (c *ClientWithResponses) CreateCaptainManifestsV1CaptainManifestsPostWithResponse(ctx context.Context, body CreateCaptainManifestsV1CaptainManifestsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCaptainManifestsV1CaptainManifestsPostResponse, error) {
	rsp, err := c.CreateCaptainManifestsV1CaptainManifestsPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCaptainManifestsV1CaptainManifestsPostResponse(rsp)
}

// DeleteChiselNodesV1ChiselDeleteWithBodyWithResponse request with arbitrary body returning *DeleteChiselNodesV1ChiselDeleteResponse
func (c *ClientWithResponses) DeleteChiselNodesV1ChiselDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteChiselNodesV1ChiselDeleteResponse, error) {
	rsp, err := c.DeleteChiselNodesV1ChiselDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteChiselNodesV1ChiselDeleteResponse(rsp)
}

func (c *ClientWithResponses) DeleteChiselNodesV1ChiselDeleteWithResponse(ctx context.Context, body DeleteChiselNodesV1ChiselDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteChiselNodesV1ChiselDeleteResponse, error) {
	rsp, err := c.DeleteChiselNodesV1ChiselDelete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteChiselNodesV1ChiselDeleteResponse(rsp)
}

// CreateChiselNodesV1ChiselPostWithBodyWithResponse request with arbitrary body returning *CreateChiselNodesV1ChiselPostResponse
func (c *ClientWithResponses) CreateChiselNodesV1ChiselPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateChiselNodesV1ChiselPostResponse, error) {
	rsp, err := c.CreateChiselNodesV1ChiselPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateChiselNodesV1ChiselPostResponse(rsp)
}

func (c *ClientWithResponses) CreateChiselNodesV1ChiselPostWithResponse(ctx context.Context, body CreateChiselNodesV1ChiselPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateChiselNodesV1ChiselPostResponse, error) {
	rsp, err := c.CreateChiselNodesV1ChiselPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateChiselNodesV1ChiselPostResponse(rsp)
}

// GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBodyWithResponse request with arbitrary body returning *GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse
func (c *ClientWithResponses) GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse, error) {
	rsp, err := c.GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse(rsp)
}

func (c *ClientWithResponses) GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithResponse(ctx context.Context, body GetWorkflowRunStatusV1GithubWorkflowRunStatusPostJSONRequestBody, reqEditors ...RequestEditorFn) (*GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse, error) {
	rsp, err := c.GetWorkflowRunStatusV1GithubWorkflowRunStatusPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse(rsp)
}

// NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBodyWithResponse request with arbitrary body returning *NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse
func (c *ClientWithResponses) NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse, error) {
	rsp, err := c.NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse(rsp)
}

func (c *ClientWithResponses) NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithResponse(ctx context.Context, body NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse, error) {
	rsp, err := c.NukeAwsCaptainAccountV1NukeAwsCaptainAccountDelete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse(rsp)
}

// NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBodyWithResponse request with arbitrary body returning *NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse
func (c *ClientWithResponses) NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse, error) {
	rsp, err := c.NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse(rsp)
}

func (c *ClientWithResponses) NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithResponse(ctx context.Context, body NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse, error) {
	rsp, err := c.NukeCaptainDomainDataV1NukeCaptainDomainDataDelete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse(rsp)
}

// CreateOpsgeniealertsManifestV1OpsgeniePostWithBodyWithResponse request with arbitrary body returning *CreateOpsgeniealertsManifestV1OpsgeniePostResponse
func (c *ClientWithResponses) CreateOpsgeniealertsManifestV1OpsgeniePostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOpsgeniealertsManifestV1OpsgeniePostResponse, error) {
	rsp, err := c.CreateOpsgeniealertsManifestV1OpsgeniePostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOpsgeniealertsManifestV1OpsgeniePostResponse(rsp)
}

func (c *ClientWithResponses) CreateOpsgeniealertsManifestV1OpsgeniePostWithResponse(ctx context.Context, body CreateOpsgeniealertsManifestV1OpsgeniePostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOpsgeniealertsManifestV1OpsgeniePostResponse, error) {
	rsp, err := c.CreateOpsgeniealertsManifestV1OpsgeniePost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOpsgeniealertsManifestV1OpsgeniePostResponse(rsp)
}

// ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBodyWithResponse request with arbitrary body returning *ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse
func (c *ClientWithResponses) ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse, error) {
	rsp, err := c.ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse(rsp)
}

func (c *ClientWithResponses) ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithResponse(ctx context.Context, body ResetGithubOrganizationV1ResetGithubOrganizationDeleteJSONRequestBody, reqEditors ...RequestEditorFn) (*ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse, error) {
	rsp, err := c.ResetGithubOrganizationV1ResetGithubOrganizationDelete(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse(rsp)
}

// CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBodyWithResponse request with arbitrary body returning *CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse
func (c *ClientWithResponses) CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse, error) {
	rsp, err := c.CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse(rsp)
}

func (c *ClientWithResponses) CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithResponse(ctx context.Context, body CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse, error) {
	rsp, err := c.CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse(rsp)
}

// HelloV1StorageBucketsPostWithBodyWithResponse request with arbitrary body returning *HelloV1StorageBucketsPostResponse
func (c *ClientWithResponses) HelloV1StorageBucketsPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HelloV1StorageBucketsPostResponse, error) {
	rsp, err := c.HelloV1StorageBucketsPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHelloV1StorageBucketsPostResponse(rsp)
}

func (c *ClientWithResponses) HelloV1StorageBucketsPostWithResponse(ctx context.Context, body HelloV1StorageBucketsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*HelloV1StorageBucketsPostResponse, error) {
	rsp, err := c.HelloV1StorageBucketsPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHelloV1StorageBucketsPostResponse(rsp)
}

// VersionVersionGetWithResponse request returning *VersionVersionGetResponse
func (c *ClientWithResponses) VersionVersionGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*VersionVersionGetResponse, error) {
	rsp, err := c.VersionVersionGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseVersionVersionGetResponse(rsp)
}

// ParseCreateCaptainManifestsV1CaptainManifestsPostResponse parses an HTTP response from a CreateCaptainManifestsV1CaptainManifestsPostWithResponse call
func ParseCreateCaptainManifestsV1CaptainManifestsPostResponse(rsp *http.Response) (*CreateCaptainManifestsV1CaptainManifestsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCaptainManifestsV1CaptainManifestsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseDeleteChiselNodesV1ChiselDeleteResponse parses an HTTP response from a DeleteChiselNodesV1ChiselDeleteWithResponse call
func ParseDeleteChiselNodesV1ChiselDeleteResponse(rsp *http.Response) (*DeleteChiselNodesV1ChiselDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteChiselNodesV1ChiselDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateChiselNodesV1ChiselPostResponse parses an HTTP response from a CreateChiselNodesV1ChiselPostWithResponse call
func ParseCreateChiselNodesV1ChiselPostResponse(rsp *http.Response) (*CreateChiselNodesV1ChiselPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateChiselNodesV1ChiselPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse parses an HTTP response from a GetWorkflowRunStatusV1GithubWorkflowRunStatusPostWithResponse call
func ParseGetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse(rsp *http.Response) (*GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkflowRunStatusV1GithubWorkflowRunStatusPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse parses an HTTP response from a NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteWithResponse call
func ParseNukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse(rsp *http.Response) (*NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NukeAwsCaptainAccountV1NukeAwsCaptainAccountDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse parses an HTTP response from a NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteWithResponse call
func ParseNukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse(rsp *http.Response) (*NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &NukeCaptainDomainDataV1NukeCaptainDomainDataDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateOpsgeniealertsManifestV1OpsgeniePostResponse parses an HTTP response from a CreateOpsgeniealertsManifestV1OpsgeniePostWithResponse call
func ParseCreateOpsgeniealertsManifestV1OpsgeniePostResponse(rsp *http.Response) (*CreateOpsgeniealertsManifestV1OpsgeniePostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOpsgeniealertsManifestV1OpsgeniePostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse parses an HTTP response from a ResetGithubOrganizationV1ResetGithubOrganizationDeleteWithResponse call
func ParseResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse(rsp *http.Response) (*ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResetGithubOrganizationV1ResetGithubOrganizationDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse parses an HTTP response from a CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostWithResponse call
func ParseCreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse(rsp *http.Response) (*CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCredentialsForAwsCaptainAccountV1SetupAwsAccountCredentialsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseHelloV1StorageBucketsPostResponse parses an HTTP response from a HelloV1StorageBucketsPostWithResponse call
func ParseHelloV1StorageBucketsPostResponse(rsp *http.Response) (*HelloV1StorageBucketsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HelloV1StorageBucketsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseVersionVersionGetResponse parses an HTTP response from a VersionVersionGetWithResponse call
func ParseVersionVersionGetResponse(rsp *http.Response) (*VersionVersionGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &VersionVersionGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
